### PR TITLE
Fix witness distance display

### LINKED ISSUE #127: Valid witness showing distance as "Too Far"
A witness is displaying as valid in the PoC receipt transaction witness list while also showing distance as 'Too Far' which would imply it is invalid. The hotspot did receive witness rewards so this may be a display issue on Explorer. Example transaction: b6YpF51lZl8GJ28Zteah53xTjx0ec9OiGXMdY7TTvaE

txnb6YpF51lZl8GJ28Zteah53xTjx0ec9OiGXMdY7TTvaE

### PR DESCRIPTION
**Pull request by danielcolinjames**
This update fixes the distance display in 2 ways:
- the logic now matches how the backend check works (not checking for "too far")
- it now uses the correct resolution that gets returned in the `poc_v4_parent_res` chain variable, instead of a hardcoded resolution 12 check

We can improve on this again for #133  but for now this should fix #127

### CODE REVIEW

File: components/Hotspots/utils.js [hunk 1]
```diff
@@ -6,7 +6,7 @@ export const formatHotspotName = (dashedName) =>
 
 export const formatDistance = (meters) => {
   if (meters < 1000) {
-    return meters.toLocaleString() + ' m'
+    return meters.toLocaleString(undefined, { maximumFractionDigits: 2 }) + ' m'
```
Comment (allenan) [inline components/Hotspots/utils.js:9]: instead of undefined, would it be better to specify the `en-US` locale?

Comment (danielcolinjames) [reply components/Hotspots/utils.js:9]: I think undefined just defaults to the user's locale right? I figured that's probably better for things like different comma separator rules, different fraction symbols etc. that show up in different languages

Comment (allenan) [reply components/Hotspots/utils.js:9]: that's fine then, if that's the case

File: components/Txns/PocReceiptsV1.js [hunk 2]
```diff
@@ -194,35 +232,59 @@ const PocReceiptsV1 = ({ txn, h3exclusionCells, h3maxHopCells }) => (
...
                                       : ''
 
-                                    const witnessDistInH3Res12Cells = h3Distance(
-                                      pDistance,
-                                      w.location,
+                                    let wLocation = w.location
+
+                                    // convert witness h3 location and challenge participant h3 location to the correct h3 resolution as set by the poc_v4_parent_res chain var
+                                    if (
+                                      pocH3CellResolution <
```
Comment (allenan) [inline components/Txns/PocReceiptsV1.js:245]: should one of these cases be `<=` or `>=` to handle the case where they're equal? even if that's rare

File: components/Hotspots/utils.js (hunk 1 above)
Comment (danielcolinjames) [reply components/Hotspots/utils.js:9]: yeah looked into it:
>// Use the host default language with options for number formatting
var num = 30000.65;
console.log(num.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2}));
// → "30,000.65" where English is the default language, or
// → "30.000,65" where German is the default language, or
// → "30 000,65" where French is the default language

from [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString)

File: components/Txns/PocReceiptsV1.js (hunk 2 above)
Comment (danielcolinjames) [reply components/Txns/PocReceiptsV1.js:245]: it's probably not written in the most intuitive way, but I purposely didn't add an else here because if the resolutions are the same, then pLocation can just stay as the value it gets set at initially instead of being converted to the correct resolution

Comment (allenan) [reply components/Txns/PocReceiptsV1.js:245]: ok, wasn't entirely sure what was happening in there

**Review by allenan — APPROVED** [review]
looks good
