### PR TITLE
fix search to work with other item types

### LINKED ISSUE #421: search by account address in beta
unable to search by account address in beta explorer

### PR DESCRIPTION
**Pull request by allenan**
closes #421

### CODE REVIEW

File: hooks/useSelectedTxn.js [hunk 1]
```diff
@@ -20,7 +18,7 @@ const useSelectedTxn = () => {
         payload: { ...txn },
       })
     },
-    [dispatch, history],
+    [dispatch],
```
Comment (allenan) [inline hooks/useSelectedTxn.js:21]: i noticed this function doesn't do the history push anymore so I removed history as a dep from this hook. wanted to make sure it's intentional that we do the history pushing separate from this txn?

Comment (danielcolinjames) [reply hooks/useSelectedTxn.js:21]: oh yeah I'm fairly sure I removed that because I was seeing it duplicated if you got there from a `<Link />` (you had to hit "back" twice in the browser after landing on a transaction because the first back would take you to the same page you were already on)

I think it's better if we can avoid using `history.push` wherever possible, because when we eventually get i18n fully integrated, the `<Link />` from `react-router-i18n` (or whatever the package is) will automatically take care of adding the correct localization to the path, which I think we'd have to do manually somehow with `history.push`

**Review by danielcolinjames — APPROVED** [review]
nice! works well and code looks good 🚢
